
lobby:
  - lobby

db:
  enabled: false
  jdbcurl: ''
  username: ''
  password: ''


rcon:
  port: 26055
  password: '12345'

automessage:
  interval: 60
  messages:
    - 'Testowa wiadomosc 1'
    - 'testowa wiadomosc 2'
